frontend_news_one_ajax:
    path:     /ajax/{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/News:ajaxOne" }

frontend_news_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/News:one" }