frontend_director_index:
    path:     /content
    defaults: { _controller: "SiteMainBundle:Frontend/Director:index" }

frontend_director_one:
    path:     /{slug}
    defaults: { _controller: "SiteMainBundle:Frontend/Director:one" }