<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function findAllArray() {
        $gallery = $this->findAll();
        $galleryArray = array();

        foreach($gallery as $g) {
            $galleryArray[$g->getDate()->format('Y')] = array();
            $galleryArray[$g->getDate()->format('Y')]['type'] = 'year';
            $galleryArray[$g->getDate()->format('Y')]['value'] = $g->getDate()->format('Y');
        }

        return $galleryArray;
    }
}
