<?php

namespace Site\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialActivitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialActivitiesRepository extends EntityRepository
{
    /**
     * Поис всех слайдеров, где есть только изображения
     *
     * @return array|bool
     */
    public function findByOnlyImage(){
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT s FROM SiteMainBundle:SocialActivities s
            WHERE s.main = 1 AND s.video IS NULL
            ORDER BY s.id DESC
        ');

        if(count($query->getResult()) > 0){
            return $query->getResult();
        }

        return false;
    }
}
